name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libqpid-proton-cpp12-dev libsqlite3-dev

    - name: Install Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        make
        sudo make install    

    - name: Setup Java for ActiveMQ
      uses: actions/setup-java@v1
      with:
        java-version: '11'  # ActiveMQ 5.x requires Java 8 or later

    - name: Download and Run ActiveMQ
      run: |
        wget https://archive.apache.org/dist/activemq/5.18.3/apache-activemq-5.18.3-bin.tar.gz
        tar xzf apache-activemq-5.18.3-bin.tar.gz
        apache-activemq-5.18.3/bin/activemq start    

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        ./build/MessageBrokerClientTest
