name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libqpid-proton-cpp12-dev libsqlite3-dev

    - name: Install Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        make
        sudo make install    

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        ./build/MessageBrokerClientTest
